import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Shape(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/source/mastershape.glb');
	const { actions } = useAnimations(animations, group);
	return (
<<<<<<< Updated upstream
		<group ref={group} {...props} dispose={null}>
			<group name='Sketchfab_Scene'>
				<group
					name='Sketchfab_model'
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.227}
				>
					<group name='root'>
						<group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
							<group
								name='Cylinder_0'
								position={[1.811, 3.009, 1.281]}
								scale={0.127}
							>
								<mesh
									name='Object_4'
									castShadow
									receiveShadow
									geometry={nodes.Object_4.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder001_2'
								position={[-1.811, 3.009, -1.281]}
								scale={0.127}
							>
								<mesh
									name='Object_6'
									castShadow
									receiveShadow
									geometry={nodes.Object_6.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder002_4'
								position={[1.281, 3.009, -1.811]}
								scale={0.127}
							>
								<mesh
									name='Object_8'
									castShadow
									receiveShadow
									geometry={nodes.Object_8.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder003_6'
								position={[-1.281, 3.009, 1.811]}
								scale={0.127}
							>
								<mesh
									name='Object_10'
									castShadow
									receiveShadow
									geometry={nodes.Object_10.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder004_8'
								position={[2.187, 3.009, -0.374]}
								scale={0.127}
							>
								<mesh
									name='Object_12'
									castShadow
									receiveShadow
									geometry={nodes.Object_12.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder005_10'
								position={[-2.187, 3.009, 0.374]}
								scale={0.127}
							>
								<mesh
									name='Object_14'
									castShadow
									receiveShadow
									geometry={nodes.Object_14.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder006_12'
								position={[-0.374, 3.009, -2.187]}
								scale={0.127}
							>
								<mesh
									name='Object_16'
									castShadow
									receiveShadow
									geometry={nodes.Object_16.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder007_14'
								position={[0.374, 3.009, 2.187]}
								scale={0.127}
							>
								<mesh
									name='Object_18'
									castShadow
									receiveShadow
									geometry={nodes.Object_18.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder008_16'
								position={[2.164, 3.009, 0.491]}
								scale={0.127}
							>
								<mesh
									name='Object_20'
									castShadow
									receiveShadow
									geometry={nodes.Object_20.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder009_18'
								position={[-2.164, 3.009, -0.491]}
								scale={0.127}
							>
								<mesh
									name='Object_22'
									castShadow
									receiveShadow
									geometry={nodes.Object_22.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder010_20'
								position={[0.491, 3.009, -2.164]}
								scale={0.127}
							>
								<mesh
									name='Object_24'
									castShadow
									receiveShadow
									geometry={nodes.Object_24.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder011_22'
								position={[-0.491, 3.009, 2.164]}
								scale={0.127}
							>
								<mesh
									name='Object_26'
									castShadow
									receiveShadow
									geometry={nodes.Object_26.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder012_24'
								position={[1.877, 3.009, -1.183]}
								scale={0.127}
							>
								<mesh
									name='Object_28'
									castShadow
									receiveShadow
									geometry={nodes.Object_28.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder013_26'
								position={[-1.877, 3.009, 1.183]}
								scale={0.127}
							>
								<mesh
									name='Object_30'
									castShadow
									receiveShadow
									geometry={nodes.Object_30.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder014_28'
								position={[-1.183, 3.009, -1.877]}
								scale={0.127}
							>
								<mesh
									name='Object_32'
									castShadow
									receiveShadow
									geometry={nodes.Object_32.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder015_30'
								position={[1.183, 3.009, 1.877]}
								scale={0.127}
							>
								<mesh
									name='Object_34'
									castShadow
									receiveShadow
									geometry={nodes.Object_34.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder016_32'
								position={[2.026, 3.009, 0.904]}
								scale={0.127}
							>
								<mesh
									name='Object_36'
									castShadow
									receiveShadow
									geometry={nodes.Object_36.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder017_34'
								position={[-2.026, 3.009, -0.904]}
								scale={0.127}
							>
								<mesh
									name='Object_38'
									castShadow
									receiveShadow
									geometry={nodes.Object_38.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder018_36'
								position={[0.904, 3.009, -2.026]}
								scale={0.127}
							>
								<mesh
									name='Object_40'
									castShadow
									receiveShadow
									geometry={nodes.Object_40.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder019_38'
								position={[-0.904, 3.009, 2.026]}
								scale={0.127}
							>
								<mesh
									name='Object_42'
									castShadow
									receiveShadow
									geometry={nodes.Object_42.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder020_40'
								position={[2.072, 3.009, -0.794]}
								scale={0.127}
							>
								<mesh
									name='Object_44'
									castShadow
									receiveShadow
									geometry={nodes.Object_44.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder021_42'
								position={[-2.072, 3.009, 0.794]}
								scale={0.127}
							>
								<mesh
									name='Object_46'
									castShadow
									receiveShadow
									geometry={nodes.Object_46.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder022_44'
								position={[-0.794, 3.009, -2.072]}
								scale={0.127}
							>
								<mesh
									name='Object_48'
									castShadow
									receiveShadow
									geometry={nodes.Object_48.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder023_46'
								position={[0.794, 3.009, 2.072]}
								scale={0.127}
							>
								<mesh
									name='Object_50'
									castShadow
									receiveShadow
									geometry={nodes.Object_50.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder024_48'
								position={[2.218, 3.009, 0.059]}
								scale={0.127}
							>
								<mesh
									name='Object_52'
									castShadow
									receiveShadow
									geometry={nodes.Object_52.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder025_50'
								position={[-2.218, 3.009, -0.059]}
								scale={0.127}
							>
								<mesh
									name='Object_54'
									castShadow
									receiveShadow
									geometry={nodes.Object_54.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder026_52'
								position={[0.059, 3.009, -2.218]}
								scale={0.127}
							>
								<mesh
									name='Object_56'
									castShadow
									receiveShadow
									geometry={nodes.Object_56.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder027_54'
								position={[-0.059, 3.009, 2.218]}
								scale={0.127}
							>
								<mesh
									name='Object_58'
									castShadow
									receiveShadow
									geometry={nodes.Object_58.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder028_56'
								position={[1.61, 3.009, -1.526]}
								scale={0.127}
							>
								<mesh
									name='Object_60'
									castShadow
									receiveShadow
									geometry={nodes.Object_60.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder029_58'
								position={[-1.61, 3.009, 1.526]}
								scale={0.127}
							>
								<mesh
									name='Object_62'
									castShadow
									receiveShadow
									geometry={nodes.Object_62.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder030_60'
								position={[-1.526, 3.009, -1.61]}
								scale={0.127}
							>
								<mesh
									name='Object_64'
									castShadow
									receiveShadow
									geometry={nodes.Object_64.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder031_62'
								position={[1.526, 3.009, 1.61]}
								scale={0.127}
							>
								<mesh
									name='Object_66'
									castShadow
									receiveShadow
									geometry={nodes.Object_66.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder032_64'
								position={[1.928, 3.009, 1.098]}
								scale={0.127}
							>
								<mesh
									name='Object_68'
									castShadow
									receiveShadow
									geometry={nodes.Object_68.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder033_66'
								position={[-1.928, 3.009, -1.098]}
								scale={0.127}
							>
								<mesh
									name='Object_70'
									castShadow
									receiveShadow
									geometry={nodes.Object_70.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder034_68'
								position={[1.098, 3.009, -1.928]}
								scale={0.127}
							>
								<mesh
									name='Object_72'
									castShadow
									receiveShadow
									geometry={nodes.Object_72.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder035_70'
								position={[-1.098, 3.009, 1.928]}
								scale={0.127}
							>
								<mesh
									name='Object_74'
									castShadow
									receiveShadow
									geometry={nodes.Object_74.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder036_72'
								position={[2.14, 3.009, -0.587]}
								scale={0.127}
							>
								<mesh
									name='Object_76'
									castShadow
									receiveShadow
									geometry={nodes.Object_76.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder037_74'
								position={[-2.14, 3.009, 0.587]}
								scale={0.127}
							>
								<mesh
									name='Object_78'
									castShadow
									receiveShadow
									geometry={nodes.Object_78.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder038_76'
								position={[-0.587, 3.009, -2.14]}
								scale={0.127}
							>
								<mesh
									name='Object_80'
									castShadow
									receiveShadow
									geometry={nodes.Object_80.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder039_78'
								position={[0.587, 3.009, 2.14]}
								scale={0.127}
							>
								<mesh
									name='Object_82'
									castShadow
									receiveShadow
									geometry={nodes.Object_82.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder040_80'
								position={[2.201, 3.009, 0.276]}
								scale={0.127}
							>
								<mesh
									name='Object_84'
									castShadow
									receiveShadow
									geometry={nodes.Object_84.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder041_82'
								position={[-2.201, 3.009, -0.276]}
								scale={0.127}
							>
								<mesh
									name='Object_86'
									castShadow
									receiveShadow
									geometry={nodes.Object_86.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder042_84'
								position={[0.276, 3.009, -2.201]}
								scale={0.127}
							>
								<mesh
									name='Object_88'
									castShadow
									receiveShadow
									geometry={nodes.Object_88.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder043_86'
								position={[-0.276, 3.009, 2.201]}
								scale={0.127}
							>
								<mesh
									name='Object_90'
									castShadow
									receiveShadow
									geometry={nodes.Object_90.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder044_88'
								position={[1.752, 3.009, -1.361]}
								scale={0.127}
							>
								<mesh
									name='Object_92'
									castShadow
									receiveShadow
									geometry={nodes.Object_92.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder045_90'
								position={[-1.752, 3.009, 1.361]}
								scale={0.127}
							>
								<mesh
									name='Object_94'
									castShadow
									receiveShadow
									geometry={nodes.Object_94.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder046_92'
								position={[-1.361, 3.009, -1.752]}
								scale={0.127}
							>
								<mesh
									name='Object_96'
									castShadow
									receiveShadow
									geometry={nodes.Object_96.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder047_94'
								position={[1.361, 3.009, 1.752]}
								scale={0.127}
							>
								<mesh
									name='Object_98'
									castShadow
									receiveShadow
									geometry={nodes.Object_98.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder048_96'
								position={[2.105, 3.009, 0.701]}
								scale={0.127}
							>
								<mesh
									name='Object_100'
									castShadow
									receiveShadow
									geometry={nodes.Object_100.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder049_98'
								position={[-2.105, 3.009, -0.701]}
								scale={0.127}
							>
								<mesh
									name='Object_102'
									castShadow
									receiveShadow
									geometry={nodes.Object_102.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder050_100'
								position={[0.701, 3.009, -2.105]}
								scale={0.127}
							>
								<mesh
									name='Object_104'
									castShadow
									receiveShadow
									geometry={nodes.Object_104.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder051_102'
								position={[-0.701, 3.009, 2.105]}
								scale={0.127}
							>
								<mesh
									name='Object_106'
									castShadow
									receiveShadow
									geometry={nodes.Object_106.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder052_104'
								position={[1.984, 3.009, -0.993]}
								scale={0.127}
							>
								<mesh
									name='Object_108'
									castShadow
									receiveShadow
									geometry={nodes.Object_108.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder053_106'
								position={[-1.984, 3.009, 0.993]}
								scale={0.127}
							>
								<mesh
									name='Object_110'
									castShadow
									receiveShadow
									geometry={nodes.Object_110.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder054_108'
								position={[-0.993, 3.009, -1.984]}
								scale={0.127}
							>
								<mesh
									name='Object_112'
									castShadow
									receiveShadow
									geometry={nodes.Object_112.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder055_110'
								position={[0.993, 3.009, 1.984]}
								scale={0.127}
							>
								<mesh
									name='Object_114'
									castShadow
									receiveShadow
									geometry={nodes.Object_114.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder056_112'
								position={[2.213, 3.009, -0.158]}
								scale={0.127}
							>
								<mesh
									name='Object_116'
									castShadow
									receiveShadow
									geometry={nodes.Object_116.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder057_114'
								position={[-2.213, 3.009, 0.158]}
								scale={0.127}
							>
								<mesh
									name='Object_118'
									castShadow
									receiveShadow
									geometry={nodes.Object_118.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder058_116'
								position={[-0.158, 3.009, -2.213]}
								scale={0.127}
							>
								<mesh
									name='Object_120'
									castShadow
									receiveShadow
									geometry={nodes.Object_120.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder059_118'
								position={[0.158, 3.009, 2.213]}
								scale={0.127}
							>
								<mesh
									name='Object_122'
									castShadow
									receiveShadow
									geometry={nodes.Object_122.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder060_120'
								position={[1.453, 3.009, -1.677]}
								scale={0.127}
							>
								<mesh
									name='Object_124'
									castShadow
									receiveShadow
									geometry={nodes.Object_124.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder061_122'
								position={[-1.453, 3.009, 1.677]}
								scale={0.127}
							>
								<mesh
									name='Object_126'
									castShadow
									receiveShadow
									geometry={nodes.Object_126.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder062_124'
								position={[-1.677, 3.009, -1.453]}
								scale={0.127}
							>
								<mesh
									name='Object_128'
									castShadow
									receiveShadow
									geometry={nodes.Object_128.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder063_126'
								position={[1.677, 3.009, 1.453]}
								scale={0.127}
							>
								<mesh
									name='Object_130'
									castShadow
									receiveShadow
									geometry={nodes.Object_130.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder064_128'
								position={[1.872, 3.009, 1.191]}
								scale={0.127}
							>
								<mesh
									name='Object_132'
									castShadow
									receiveShadow
									geometry={nodes.Object_132.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder065_130'
								position={[-1.872, 3.009, -1.191]}
								scale={0.127}
							>
								<mesh
									name='Object_134'
									castShadow
									receiveShadow
									geometry={nodes.Object_134.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder066_132'
								position={[1.191, 3.009, -1.872]}
								scale={0.127}
							>
								<mesh
									name='Object_136'
									castShadow
									receiveShadow
									geometry={nodes.Object_136.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder067_134'
								position={[-1.191, 3.009, 1.872]}
								scale={0.127}
							>
								<mesh
									name='Object_138'
									castShadow
									receiveShadow
									geometry={nodes.Object_138.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder068_136'
								position={[2.166, 3.009, -0.481]}
								scale={0.127}
							>
								<mesh
									name='Object_140'
									castShadow
									receiveShadow
									geometry={nodes.Object_140.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder069_138'
								position={[-2.166, 3.009, 0.481]}
								scale={0.127}
							>
								<mesh
									name='Object_142'
									castShadow
									receiveShadow
									geometry={nodes.Object_142.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder070_140'
								position={[-0.481, 3.009, -2.166]}
								scale={0.127}
							>
								<mesh
									name='Object_144'
									castShadow
									receiveShadow
									geometry={nodes.Object_144.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder071_142'
								position={[0.481, 3.009, 2.166]}
								scale={0.127}
							>
								<mesh
									name='Object_146'
									castShadow
									receiveShadow
									geometry={nodes.Object_146.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder072_144'
								position={[2.185, 3.009, 0.384]}
								scale={0.127}
							>
								<mesh
									name='Object_148'
									castShadow
									receiveShadow
									geometry={nodes.Object_148.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder073_146'
								position={[-2.185, 3.009, -0.384]}
								scale={0.127}
							>
								<mesh
									name='Object_150'
									castShadow
									receiveShadow
									geometry={nodes.Object_150.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder074_148'
								position={[0.384, 3.009, -2.185]}
								scale={0.127}
							>
								<mesh
									name='Object_152'
									castShadow
									receiveShadow
									geometry={nodes.Object_152.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder075_150'
								position={[-0.384, 3.009, 2.185]}
								scale={0.127}
							>
								<mesh
									name='Object_154'
									castShadow
									receiveShadow
									geometry={nodes.Object_154.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder076_152'
								position={[1.817, 3.009, -1.274]}
								scale={0.127}
							>
								<mesh
									name='Object_156'
									castShadow
									receiveShadow
									geometry={nodes.Object_156.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder077_154'
								position={[-1.817, 3.009, 1.274]}
								scale={0.127}
							>
								<mesh
									name='Object_158'
									castShadow
									receiveShadow
									geometry={nodes.Object_158.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder078_156'
								position={[-1.274, 3.009, -1.817]}
								scale={0.127}
							>
								<mesh
									name='Object_160'
									castShadow
									receiveShadow
									geometry={nodes.Object_160.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder079_158'
								position={[1.274, 3.009, 1.817]}
								scale={0.127}
							>
								<mesh
									name='Object_162'
									castShadow
									receiveShadow
									geometry={nodes.Object_162.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder080_160'
								position={[2.068, 3.009, 0.803]}
								scale={0.127}
							>
								<mesh
									name='Object_164'
									castShadow
									receiveShadow
									geometry={nodes.Object_164.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder081_162'
								position={[-2.068, 3.009, -0.803]}
								scale={0.127}
							>
								<mesh
									name='Object_166'
									castShadow
									receiveShadow
									geometry={nodes.Object_166.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder082_164'
								position={[0.803, 3.009, -2.068]}
								scale={0.127}
							>
								<mesh
									name='Object_168'
									castShadow
									receiveShadow
									geometry={nodes.Object_168.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder083_166'
								position={[-0.803, 3.009, 2.068]}
								scale={0.127}
							>
								<mesh
									name='Object_170'
									castShadow
									receiveShadow
									geometry={nodes.Object_170.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder084_168'
								position={[2.03, 3.009, -0.895]}
								scale={0.127}
							>
								<mesh
									name='Object_172'
									castShadow
									receiveShadow
									geometry={nodes.Object_172.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder085_170'
								position={[-2.03, 3.009, 0.895]}
								scale={0.127}
							>
								<mesh
									name='Object_174'
									castShadow
									receiveShadow
									geometry={nodes.Object_174.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder086_172'
								position={[-0.895, 3.009, -2.03]}
								scale={0.127}
							>
								<mesh
									name='Object_176'
									castShadow
									receiveShadow
									geometry={nodes.Object_176.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder087_174'
								position={[0.895, 3.009, 2.03]}
								scale={0.127}
							>
								<mesh
									name='Object_178'
									castShadow
									receiveShadow
									geometry={nodes.Object_178.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder088_176'
								position={[2.218, 3.009, -0.05]}
								scale={0.127}
							>
								<mesh
									name='Object_180'
									castShadow
									receiveShadow
									geometry={nodes.Object_180.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder089_178'
								position={[-2.218, 3.009, 0.05]}
								scale={0.127}
							>
								<mesh
									name='Object_182'
									castShadow
									receiveShadow
									geometry={nodes.Object_182.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder090_180'
								position={[-0.05, 3.009, -2.218]}
								scale={0.127}
							>
								<mesh
									name='Object_184'
									castShadow
									receiveShadow
									geometry={nodes.Object_184.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder091_182'
								position={[0.05, 3.009, 2.218]}
								scale={0.127}
							>
								<mesh
									name='Object_186'
									castShadow
									receiveShadow
									geometry={nodes.Object_186.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder092_184'
								position={[1.533, 3.009, -1.603]}
								scale={0.127}
							>
								<mesh
									name='Object_188'
									castShadow
									receiveShadow
									geometry={nodes.Object_188.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder093_186'
								position={[-1.533, 3.009, 1.603]}
								scale={0.127}
							>
								<mesh
									name='Object_190'
									castShadow
									receiveShadow
									geometry={nodes.Object_190.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder094_188'
								position={[-1.603, 3.009, -1.533]}
								scale={0.127}
							>
								<mesh
									name='Object_192'
									castShadow
									receiveShadow
									geometry={nodes.Object_192.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder095_190'
								position={[1.603, 3.009, 1.533]}
								scale={0.127}
							>
								<mesh
									name='Object_194'
									castShadow
									receiveShadow
									geometry={nodes.Object_194.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder096_192'
								position={[1.98, 3.009, 1.002]}
								scale={0.127}
							>
								<mesh
									name='Object_196'
									castShadow
									receiveShadow
									geometry={nodes.Object_196.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder097_194'
								position={[-1.98, 3.009, -1.002]}
								scale={0.127}
							>
								<mesh
									name='Object_198'
									castShadow
									receiveShadow
									geometry={nodes.Object_198.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder098_196'
								position={[1.002, 3.009, -1.98]}
								scale={0.127}
							>
								<mesh
									name='Object_200'
									castShadow
									receiveShadow
									geometry={nodes.Object_200.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder099_198'
								position={[-1.002, 3.009, 1.98]}
								scale={0.127}
							>
								<mesh
									name='Object_202'
									castShadow
									receiveShadow
									geometry={nodes.Object_202.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder100_200'
								position={[2.108, 3.009, -0.691]}
								scale={0.127}
							>
								<mesh
									name='Object_204'
									castShadow
									receiveShadow
									geometry={nodes.Object_204.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder101_202'
								position={[-2.108, 3.009, 0.691]}
								scale={0.127}
							>
								<mesh
									name='Object_206'
									castShadow
									receiveShadow
									geometry={nodes.Object_206.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder102_204'
								position={[-0.691, 3.009, -2.108]}
								scale={0.127}
							>
								<mesh
									name='Object_208'
									castShadow
									receiveShadow
									geometry={nodes.Object_208.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder103_206'
								position={[0.691, 3.009, 2.108]}
								scale={0.127}
							>
								<mesh
									name='Object_210'
									castShadow
									receiveShadow
									geometry={nodes.Object_210.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder104_208'
								position={[2.212, 3.009, 0.168]}
								scale={0.127}
							>
								<mesh
									name='Object_212'
									castShadow
									receiveShadow
									geometry={nodes.Object_212.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder105_210'
								position={[-2.212, 3.009, -0.168]}
								scale={0.127}
							>
								<mesh
									name='Object_214'
									castShadow
									receiveShadow
									geometry={nodes.Object_214.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder106_212'
								position={[0.168, 3.009, -2.212]}
								scale={0.127}
							>
								<mesh
									name='Object_216'
									castShadow
									receiveShadow
									geometry={nodes.Object_216.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder107_214'
								position={[-0.168, 3.009, 2.212]}
								scale={0.127}
							>
								<mesh
									name='Object_218'
									castShadow
									receiveShadow
									geometry={nodes.Object_218.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder108_216'
								position={[1.683, 3.009, -1.445]}
								scale={0.127}
							>
								<mesh
									name='Object_220'
									castShadow
									receiveShadow
									geometry={nodes.Object_220.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder109_218'
								position={[-1.683, 3.009, 1.445]}
								scale={0.127}
							>
								<mesh
									name='Object_222'
									castShadow
									receiveShadow
									geometry={nodes.Object_222.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder110_220'
								position={[-1.445, 3.009, -1.683]}
								scale={0.127}
							>
								<mesh
									name='Object_224'
									castShadow
									receiveShadow
									geometry={nodes.Object_224.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder111_222'
								position={[1.445, 3.009, 1.683]}
								scale={0.127}
							>
								<mesh
									name='Object_226'
									castShadow
									receiveShadow
									geometry={nodes.Object_226.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder112_224'
								position={[2.137, 3.009, 0.596]}
								scale={0.127}
							>
								<mesh
									name='Object_228'
									castShadow
									receiveShadow
									geometry={nodes.Object_228.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder113_226'
								position={[-2.137, 3.009, -0.596]}
								scale={0.127}
							>
								<mesh
									name='Object_230'
									castShadow
									receiveShadow
									geometry={nodes.Object_230.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder114_228'
								position={[0.596, 3.009, -2.137]}
								scale={0.127}
							>
								<mesh
									name='Object_232'
									castShadow
									receiveShadow
									geometry={nodes.Object_232.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder115_230'
								position={[-0.596, 3.009, 2.137]}
								scale={0.127}
							>
								<mesh
									name='Object_234'
									castShadow
									receiveShadow
									geometry={nodes.Object_234.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder116_232'
								position={[1.933, 3.009, -1.089]}
								scale={0.127}
							>
								<mesh
									name='Object_236'
									castShadow
									receiveShadow
									geometry={nodes.Object_236.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder117_234'
								position={[-1.933, 3.009, 1.089]}
								scale={0.127}
							>
								<mesh
									name='Object_238'
									castShadow
									receiveShadow
									geometry={nodes.Object_238.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder118_236'
								position={[-1.089, 3.009, -1.933]}
								scale={0.127}
							>
								<mesh
									name='Object_240'
									castShadow
									receiveShadow
									geometry={nodes.Object_240.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder119_238'
								position={[1.089, 3.009, 1.933]}
								scale={0.127}
							>
								<mesh
									name='Object_242'
									castShadow
									receiveShadow
									geometry={nodes.Object_242.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder120_240'
								position={[2.203, 3.009, -0.267]}
								scale={0.127}
							>
								<mesh
									name='Object_244'
									castShadow
									receiveShadow
									geometry={nodes.Object_244.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder121_242'
								position={[-2.203, 3.009, 0.267]}
								scale={0.127}
							>
								<mesh
									name='Object_246'
									castShadow
									receiveShadow
									geometry={nodes.Object_246.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder122_244'
								position={[-0.267, 3.009, -2.203]}
								scale={0.127}
							>
								<mesh
									name='Object_248'
									castShadow
									receiveShadow
									geometry={nodes.Object_248.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder123_246'
								position={[0.267, 3.009, 2.203]}
								scale={0.127}
							>
								<mesh
									name='Object_250'
									castShadow
									receiveShadow
									geometry={nodes.Object_250.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder124_248'
								position={[1.369, 3.009, -1.746]}
								scale={0.127}
							>
								<mesh
									name='Object_252'
									castShadow
									receiveShadow
									geometry={nodes.Object_252.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder125_250'
								position={[-1.369, 3.009, 1.746]}
								scale={0.127}
							>
								<mesh
									name='Object_254'
									castShadow
									receiveShadow
									geometry={nodes.Object_254.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder126_252'
								position={[-1.746, 3.009, -1.369]}
								scale={0.127}
							>
								<mesh
									name='Object_256'
									castShadow
									receiveShadow
									geometry={nodes.Object_256.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
							<group
								name='Cylinder127_254'
								position={[1.746, 3.009, 1.369]}
								scale={0.127}
							>
								<mesh
									name='Object_258'
									castShadow
									receiveShadow
									geometry={nodes.Object_258.geometry}
									material={materials['Scene_-_Root']}
								/>
							</group>
						</group>
					</group>
				</group>
=======
		<group {...props} dispose={null}>
			<group position={[0, 0.5, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials['Material.001']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5.geometry}
					material={materials.Material}
				/>
>>>>>>> Stashed changes
			</group>
		</group>
	);
}

useGLTF.preload('/sourcemastershape.glb');

export default Shape;
